name: SimpleInstructions
author: da123rrell
main: da123rrell\dada\MainClass
version: 3.0.0
description: says things
api: 1.13.1
commands:
    ILandbuy:
        description: Replies
        usage: "USAGE: /ILandbuy"
    IFaction:
        description: what and how to buy land
        usage: "USAGE: /IFaction"
        
