name: SimpleInstructions
author: da123rrell
main: da123rrell\dada\MainClass
version: 2.0.0
description: says thing
api: 1.13.1
commands:
    ILandbuy:
        description: Replies
    IFaction:
        description: what and how to buy land
        
